/*
 * BitMEX API
 *
 * ## REST API for the BitMEX Trading Platform  [View Changelog](/app/apiChangelog)    #### Getting Started   ##### Fetching Data  All REST endpoints are documented below. You can try out any query right from this interface.  Most table queries accept `count`, `start`, and `reverse` params. Set `reverse=true` to get rows newest-first.  Additional documentation regarding filters, timestamps, and authentication is available in [the main API documentation](https://www.bitmex.com/app/restAPI).  *All* table data is available via the [Websocket](/app/wsAPI). We highly recommend using the socket if you want to have the quickest possible data without being subject to ratelimits.  ##### Return Types  By default, all data is returned as JSON. Send `?_format=csv` to get CSV data or `?_format=xml` to get XML data.  ##### Trade Data Queries  *This is only a small subset of what is available, to get you started.*  Fill in the parameters and click the `Try it out!` button to try any of these queries.  * [Pricing Data](#!/Quote/Quote_get)  * [Trade Data](#!/Trade/Trade_get)  * [OrderBook Data](#!/OrderBook/OrderBook_getL2)  * [Settlement Data](#!/Settlement/Settlement_get)  * [Exchange Statistics](#!/Stats/Stats_history)  Every function of the BitMEX.com platform is exposed here and documented. Many more functions are available.  ##### Swagger Specification  [⇩ Download Swagger JSON](swagger.json)    ## All API Endpoints  Click to expand a section.
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@bitmex.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Position struct {
	Account              NullFloat32 `json:"account"`
	Symbol               NullString  `json:"symbol"`
	Currency             NullString  `json:"currency"`
	Underlying           NullString  `json:"underlying,omitempty"`
	QuoteCurrency        NullString  `json:"quoteCurrency,omitempty"`
	Commission           NullFloat64 `json:"commission,omitempty"`
	InitMarginReq        NullFloat64 `json:"initMarginReq,omitempty"`
	MaintMarginReq       NullFloat64 `json:"maintMarginReq,omitempty"`
	RiskLimit            NullFloat32 `json:"riskLimit,omitempty"`
	Leverage             NullFloat64 `json:"leverage,omitempty"`
	CrossMargin          NullBool    `json:"crossMargin,omitempty"`
	DeleveragePercentile NullFloat64 `json:"deleveragePercentile,omitempty"`
	RebalancedPnl        NullFloat32 `json:"rebalancedPnl,omitempty"`
	PrevRealisedPnl      NullFloat32 `json:"prevRealisedPnl,omitempty"`
	PrevUnrealisedPnl    NullFloat32 `json:"prevUnrealisedPnl,omitempty"`
	PrevClosePrice       NullFloat64 `json:"prevClosePrice,omitempty"`
	OpeningTimestamp     NullTime    `json:"openingTimestamp,omitempty"`
	OpeningQty           NullFloat32 `json:"openingQty,omitempty"`
	OpeningCost          NullFloat32 `json:"openingCost,omitempty"`
	OpeningComm          NullFloat32 `json:"openingComm,omitempty"`
	OpenOrderBuyQty      NullFloat32 `json:"openOrderBuyQty,omitempty"`
	OpenOrderBuyCost     NullFloat32 `json:"openOrderBuyCost,omitempty"`
	OpenOrderBuyPremium  NullFloat32 `json:"openOrderBuyPremium,omitempty"`
	OpenOrderSellQty     NullFloat32 `json:"openOrderSellQty,omitempty"`
	OpenOrderSellCost    NullFloat32 `json:"openOrderSellCost,omitempty"`
	OpenOrderSellPremium NullFloat32 `json:"openOrderSellPremium,omitempty"`
	ExecBuyQty           NullFloat32 `json:"execBuyQty,omitempty"`
	ExecBuyCost          NullFloat32 `json:"execBuyCost,omitempty"`
	ExecSellQty          NullFloat32 `json:"execSellQty,omitempty"`
	ExecSellCost         NullFloat32 `json:"execSellCost,omitempty"`
	ExecQty              NullFloat32 `json:"execQty,omitempty"`
	ExecCost             NullFloat32 `json:"execCost,omitempty"`
	ExecComm             NullFloat32 `json:"execComm,omitempty"`
	CurrentTimestamp     NullTime    `json:"currentTimestamp,omitempty"`
	CurrentQty           NullFloat32 `json:"currentQty,omitempty"`
	CurrentCost          NullFloat32 `json:"currentCost,omitempty"`
	CurrentComm          NullFloat32 `json:"currentComm,omitempty"`
	RealisedCost         NullFloat32 `json:"realisedCost,omitempty"`
	UnrealisedCost       NullFloat32 `json:"unrealisedCost,omitempty"`
	GrossOpenCost        NullFloat32 `json:"grossOpenCost,omitempty"`
	GrossOpenPremium     NullFloat32 `json:"grossOpenPremium,omitempty"`
	GrossExecCost        NullFloat32 `json:"grossExecCost,omitempty"`
	IsOpen               NullBool    `json:"isOpen,omitempty"`
	MarkPrice            NullFloat64 `json:"markPrice,omitempty"`
	MarkValue            NullFloat32 `json:"markValue,omitempty"`
	RiskValue            NullFloat32 `json:"riskValue,omitempty"`
	HomeNotional         NullFloat64 `json:"homeNotional,omitempty"`
	ForeignNotional      NullFloat64 `json:"foreignNotional,omitempty"`
	PosState             NullString  `json:"posState,omitempty"`
	PosCost              NullFloat32 `json:"posCost,omitempty"`
	PosCost2             NullFloat32 `json:"posCost2,omitempty"`
	PosCross             NullFloat32 `json:"posCross,omitempty"`
	PosInit              NullFloat32 `json:"posInit,omitempty"`
	PosComm              NullFloat32 `json:"posComm,omitempty"`
	PosLoss              NullFloat32 `json:"posLoss,omitempty"`
	PosMargin            NullFloat32 `json:"posMargin,omitempty"`
	PosMaint             NullFloat32 `json:"posMaint,omitempty"`
	PosAllowance         NullFloat32 `json:"posAllowance,omitempty"`
	TaxableMargin        NullFloat32 `json:"taxableMargin,omitempty"`
	InitMargin           NullFloat32 `json:"initMargin,omitempty"`
	MaintMargin          NullFloat32 `json:"maintMargin,omitempty"`
	SessionMargin        NullFloat32 `json:"sessionMargin,omitempty"`
	TargetExcessMargin   NullFloat32 `json:"targetExcessMargin,omitempty"`
	VarMargin            NullFloat32 `json:"varMargin,omitempty"`
	RealisedGrossPnl     NullFloat32 `json:"realisedGrossPnl,omitempty"`
	RealisedTax          NullFloat32 `json:"realisedTax,omitempty"`
	RealisedPnl          NullFloat32 `json:"realisedPnl,omitempty"`
	UnrealisedGrossPnl   NullFloat32 `json:"unrealisedGrossPnl,omitempty"`
	LongBankrupt         NullFloat32 `json:"longBankrupt,omitempty"`
	ShortBankrupt        NullFloat32 `json:"shortBankrupt,omitempty"`
	TaxBase              NullFloat32 `json:"taxBase,omitempty"`
	IndicativeTaxRate    NullFloat64 `json:"indicativeTaxRate,omitempty"`
	IndicativeTax        NullFloat32 `json:"indicativeTax,omitempty"`
	UnrealisedTax        NullFloat32 `json:"unrealisedTax,omitempty"`
	UnrealisedPnl        NullFloat32 `json:"unrealisedPnl,omitempty"`
	UnrealisedPnlPcnt    NullFloat64 `json:"unrealisedPnlPcnt,omitempty"`
	UnrealisedRoePcnt    NullFloat64 `json:"unrealisedRoePcnt,omitempty"`
	SimpleQty            NullFloat64 `json:"simpleQty,omitempty"`
	SimpleCost           NullFloat64 `json:"simpleCost,omitempty"`
	SimpleValue          NullFloat64 `json:"simpleValue,omitempty"`
	SimplePnl            NullFloat64 `json:"simplePnl,omitempty"`
	SimplePnlPcnt        NullFloat64 `json:"simplePnlPcnt,omitempty"`
	AvgCostPrice         NullFloat64 `json:"avgCostPrice,omitempty"`
	AvgEntryPrice        NullFloat64 `json:"avgEntryPrice,omitempty"`
	BreakEvenPrice       NullFloat64 `json:"breakEvenPrice,omitempty"`
	MarginCallPrice      NullFloat64 `json:"marginCallPrice,omitempty"`
	LiquidationPrice     NullFloat64 `json:"liquidationPrice,omitempty"`
	BankruptPrice        NullFloat64 `json:"bankruptPrice,omitempty"`
	Timestamp            NullTime    `json:"timestamp,omitempty"`
	LastPrice            NullFloat64 `json:"lastPrice,omitempty"`
	LastValue            NullFloat32 `json:"lastValue,omitempty"`
}
