/*
* BitMEX API
*
* ## REST API for the BitMEX Trading Platform  [View Changelog](/app/apiChangelog)    #### Getting Started   ##### Fetching Data  All REST endpoints are documented below. You can try out any query right from this interface.  Most table queries accept `count`, `start`, and `reverse` params. Set `reverse=true` to get rows newest-first.  Additional documentation regarding filters, timestamps, and authentication is available in [the main API documentation](https://www.bitmex.com/app/restAPI).  *All* table data is available via the [Websocket](/app/wsAPI). We highly recommend using the socket if you want to have the quickest possible data without being subject to ratelimits.  ##### Return Types  By default, all data is returned as JSON. Send `?_format=csv` to get CSV data or `?_format=xml` to get XML data.  ##### Trade Data Queries  *This is only a small subset of what is available, to get you started.*  Fill in the parameters and click the `Try it out!` button to try any of these queries.  * [Pricing Data](#!/Quote/Quote_get)  * [Trade Data](#!/Trade/Trade_get)  * [OrderBook Data](#!/OrderBook/OrderBook_getL2)  * [Settlement Data](#!/Settlement/Settlement_get)  * [Exchange Statistics](#!/Stats/Stats_history)  Every function of the BitMEX.com platform is exposed here and documented. Many more functions are available.  ##### Swagger Specification  [⇩ Download Swagger JSON](swagger.json)    ## All API Endpoints  Click to expand a section.
*
* OpenAPI spec version: 1.2.0
* Contact: support@bitmex.com
* Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Order struct {
	OrderID               NullString  `json:"orderID"`
	ClOrdID               NullString  `json:"clOrdID,omitempty"`
	ClOrdLinkID           NullString  `json:"clOrdLinkID,omitempty"`
	Account               NullFloat32 `json:"account,omitempty"`
	Symbol                NullString  `json:"symbol,omitempty"`
	Side                  NullString  `json:"side,omitempty"`
	SimpleOrderQty        NullFloat64 `json:"simpleOrderQty,omitempty"`
	OrderQty              NullFloat32 `json:"orderQty,omitempty"`
	Price                 NullFloat64 `json:"price,omitempty"`
	DisplayQty            NullFloat32 `json:"displayQty,omitempty"`
	StopPx                NullFloat64 `json:"stopPx,omitempty"`
	PegOffsetValue        NullFloat64 `json:"pegOffsetValue,omitempty"`
	PegPriceType          NullString  `json:"pegPriceType,omitempty"`
	Currency              NullString  `json:"currency,omitempty"`
	SettlCurrency         NullString  `json:"settlCurrency,omitempty"`
	OrdType               NullString  `json:"ordType,omitempty"`
	TimeInForce           NullString  `json:"timeInForce,omitempty"`
	ExecInst              NullString  `json:"execInst,omitempty"`
	ContingencyType       NullString  `json:"contingencyType,omitempty"`
	ExDestination         NullString  `json:"exDestination,omitempty"`
	OrdStatus             NullString  `json:"ordStatus,omitempty"`
	Triggered             NullString  `json:"triggered,omitempty"`
	WorkingIndicator      NullBool    `json:"workingIndicator,omitempty"`
	OrdRejReason          NullString  `json:"ordRejReason,omitempty"`
	SimpleLeavesQty       NullFloat64 `json:"simpleLeavesQty,omitempty"`
	LeavesQty             NullFloat32 `json:"leavesQty,omitempty"`
	SimpleCumQty          NullFloat64 `json:"simpleCumQty,omitempty"`
	CumQty                NullFloat32 `json:"cumQty,omitempty"`
	AvgPx                 NullFloat64 `json:"avgPx,omitempty"`
	MultiLegReportingType NullString  `json:"multiLegReportingType,omitempty"`
	Text                  NullString  `json:"text,omitempty"`
	TransactTime          NullTime    `json:"transactTime,omitempty"`
	Timestamp             NullTime    `json:"timestamp,omitempty"`
}
